
// b!drunk6.baf - Gets Gavin out into the prison entrance area  

IF
    True()
THEN
    RESPONSE #100
        CutSceneId(Player1)
        Wait(1)
        FadeToColor([20.0],0)
        ActionOverride("B!Gavin2",JumpToPoint([807.583]) 
        MultiPlayerSync()
        Wait(1)
        FadeFromColor([20.0],0)
        MoveViewObject(Player1,INSTANT)
        Wait(1)
        ActionOverride("B!Gavin2",StartDialogueNoSet(Player1)) 
END 
