
//B!GaVAMP.baf this is the vampire-Gavin's fight script
IF
	Global("C6BodhiFight","AR0809",1)
	Allegiance(Myself,NEUTRAL)
THEN
	RESPONSE #100
		Enemy()
END

/*
IF
	Die()
THEN
	RESPONSE #100
		SetGlobal("B!GavVampire","GLOBAL",3)
		DropInventory()
		DestroySelf()
END
*/

IF
	See([PC])
	Delay(12)
	Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		ReallyForceSpellDead([PC],VAMPIRE_DOMINATION)
END
